import fs from 'node:fs';
import {stories,photoURL,photoAlt,collections} from './src/stories.js';
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const [i,s] of stories.entries()){
 const next=stories[(i+1)%stories.length],dir=`dist/stories/${s.slug}`;fs.mkdirSync(dir,{recursive:true});
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#101010"><title>${escape(s.title)} — Joseph Saadeh — Concept</title><meta name="robots" content="noindex,nofollow"><meta name="description" content="${escape(s.description)}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/style.css"></head><body><a class="skip" href="#gallery">Skip to gallery</a><div class="viewfinder" aria-hidden="true"><i></i><i></i><i></i><i></i></div><header><a class="brand" href="/">JOSEPH SAADEH<span>PHOTOGRAPHY & FILM</span></a><nav aria-label="Main"><a href="/#work">All stories</a><a href="/#films">Films</a><a href="/about/">About</a><a href="/#contact">Enquire</a></nav></header><main class="story-main"><div class="story-header"><p class="eyebrow">${String(i+1).padStart(2,'0')} / ${escape(s.category).toUpperCase()}</p><h1>${escape(s.title)}<em>.</em></h1><div class="story-description"><p>${escape(s.description)}</p><p class="secondary">${escape(s.note)}</p><p class="media-note">Selected photographs by Joseph Saadeh.</p></div></div><img class="story-hero" src="${photoURL(s.cover)}" alt="${escape(photoAlt[s.cover])}" fetchpriority="high"><div class="story-gallery" id="gallery">${s.photos.map((id,j)=>`<figure><img src="${photoURL(id)}" loading="lazy" alt="${escape(photoAlt[id])}"><figcaption>FRAME ${String(j+1).padStart(2,'0')}</figcaption></figure>`).join('')}</div><div class="concept-banner">Have a day in mind? <a class="inline-link" href="/#contact">Check availability with Joseph</a></div><div class="story-end"><div><p class="eyebrow">THE NEXT STORY</p><h2><em>${escape(next.title)}</em></h2></div><a href="/stories/${next.slug}/">Open story</a></div></main><div class="story-footer"><a href="/#work">Back to the filmstrip</a><span>JOSEPH SAADEH / PHOTOGRAPHY</span><span>CONCEPT BY COPYWRK</span></div></body></html>`;
 fs.writeFileSync(`${dir}/index.html`,html);
}
fs.writeFileSync('dist/404.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Frame not found — Joseph Saadeh</title><link rel="stylesheet" href="/style.css"></head><body><main style="padding:20vh 9%"><p class="eyebrow">404 / FRAME NOT FOUND</p><h1>A missing<br><em>frame.</em></h1><a class="text-button" href="/">Back to the beginning</a></main></body></html>`);
console.log(`Generated ${stories.length} standalone story pages and a 404 page.`);

const head=(title,description)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#101010"><title>${title} — Joseph Saadeh | Concept</title><meta name="description" content="${description}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/style.css"></head><body><a class="skip" href="#content">Skip to content</a><header><a class="brand" href="/">JOSEPH SAADEH<span>PHOTOGRAPHY & FILM</span></a><nav aria-label="Main"><a href="/#work">Stories</a><a href="/#films">Films</a><a href="/about/">About</a><a href="/#contact">Enquire</a></nav></header>`;
const foot=`<div class="story-footer"><a href="/">Back to the beginning</a><span>JOSEPH SAADEH / PHOTOGRAPHY</span><span>CONCEPT BY COPYWRK</span></div></body></html>`;
fs.mkdirSync('dist/about',{recursive:true});
fs.writeFileSync('dist/about/index.html',head('About','Weddings, baptisms, events and food photography by Joseph Saadeh.')+`<main class="about-main" id="content"><p class="eyebrow">JOSEPH SAADEH / BEHIND THE FRAME</p><h1>The person<br><em>behind the lens.</em></h1><div class="about-layout"><div><img src="/assets/joseph-photo-12.jpg" alt="Bride and groom beneath an evening sky"><p class="media-note">PHOTOGRAPHY BY JOSEPH SAADEH</p></div><div><p class="eyebrow">PHOTOGRAPHY / LEBANON</p><h2>Joseph<br><em>Saadeh.</em></h2><p>Weddings, baptisms, events and food. A dedicated space for the people, celebrations and details Joseph photographs.</p><p>Explore his current work on Instagram, or get in touch about the date and place you have in mind.</p><div class="about-links"><a href="https://www.instagram.com/josephsaadeh.photography/" target="_blank" rel="noopener noreferrer">View Instagram</a><a href="https://josephsaadehphotography.pixieset.com/" target="_blank" rel="noopener noreferrer">Current portfolio</a></div><dl class="photographer-details"><div><dt>Phone</dt><dd><a href="tel:+9613560404">+961 3 560 404</a></dd></div><div><dt>Email</dt><dd><a href="mailto:josephsaadeh.photo@gmail.com">josephsaadeh.photo@gmail.com</a></dd></div><div><dt>Focus</dt><dd>Weddings · Baptisms · Events · Food</dd></div></dl><a class="text-button" href="/#contact">Check availability</a></div></div></main>`+foot);
const categories=[['weddings','Weddings','A day. A thousand feelings.','For the moments you planned and the ones you never saw coming.'],['baptisms','Baptisms','Small beginnings. Lasting memories.','A celebration of faith, family and the people closest to you.'],['events','Events','The atmosphere. The people.','The moments that make a gathering worth remembering.'],['food','Food','Every detail, considered.','A space for food, texture and the craft behind the plate.']];
for(const [slug,title,line,description] of categories){
 const dir=`dist/collections/${slug}`;fs.mkdirSync(dir,{recursive:true});
 const ids=collections[slug];
 const gallery=ids.length?`<img class="story-hero" src="${photoURL(slug==='weddings'?2:15)}" alt="${escape(photoAlt[slug==='weddings'?2:15])}" fetchpriority="high"><div class="story-gallery" id="gallery">${ids.map((id,i)=>`<figure><img src="${photoURL(id)}" alt="${escape(photoAlt[id])}" loading="lazy"><figcaption>FRAME ${String(i+1).padStart(2,'0')}</figcaption></figure>`).join('')}</div>`:`<div class="collection-empty"><p class="eyebrow">THE COLLECTION</p><p>Explore Joseph’s ${title.toLowerCase()} photography in his current portfolio.</p><div class="about-links"><a href="https://www.instagram.com/josephsaadeh.photography/" target="_blank" rel="noopener noreferrer">View Joseph’s work</a><a href="https://josephsaadehphotography.pixieset.com/" target="_blank" rel="noopener noreferrer">Current portfolio</a></div></div>`;
 fs.writeFileSync(`${dir}/index.html`,head(title,description)+`<main class="story-main" id="content"><div class="story-header"><p class="eyebrow">THROUGH THE LENS / ${title.toUpperCase()}</p><h1>${title}<em>.</em></h1><div class="story-description"><p>${line}</p><p class="secondary">${description}</p>${ids.length?'<p class="media-note">Photographs by Joseph Saadeh.</p>':''}</div></div>${gallery}<div class="story-end"><h2>Your story,<br><em>next.</em></h2><a href="/#contact">Check availability</a></div></main>`+foot);
}
