export const stories=[
 {slug:'river-light',title:'River light',category:'Couple story',cover:3,photos:[0,2,3,4,8,11],description:'A boat, an open sky, and an afternoon with nowhere else to be. A collection of quiet glances and easy laughter on the water.',note:'The water gives these photographs their rhythm. Reflections, open space, and the warmth of red against the landscape carry the story.'},
 {slug:'a-quiet-afternoon',title:'A quiet afternoon',category:'Couple story',cover:6,photos:[1,5,6,7,12,13],description:'A book shared in the grass. The light settling over the hills. Small moments that feel entirely their own.',note:'Gentle colours leave room for expression. Close portraits sit beside wider frames, letting the landscape become part of the memory.'},
 {slug:'together-in-emerald',title:'Together in emerald',category:'Celebration',cover:19,photos:[17,18,19,20,21,22],description:'Rich emerald, bright courtyards, and a little movement between the still frames. A celebration of being together.',note:'The repeating arches frame the couple, while the jewel tones bring the collection together. A balance of composed portraits and spontaneous moments.'},
 {slug:'before-the-vows',title:'Before the vows',category:'Wedding portrait',cover:25,photos:[23,24,25],description:'The final quiet moments before a new chapter. Window light, embroidered details, and a portrait worth keeping.',note:'A small portrait collection centred on light and detail. Soft curtains and deep reds give each frame its own sense of anticipation.'},
 {slug:'under-the-trees',title:'Under the trees',category:'Couple story',cover:30,photos:[26,27,28,29,30],description:'A walk beneath the trees. Pale flowers, deep green, and a story told at an unhurried pace.',note:'The canopy becomes a natural backdrop. Wider compositions hold the setting, while the closer frames stay with the people.'}
];
export const films=[{title:'A day to remember',aspect:'854 / 480',duration:'04:35',caption:'Wedding film · 4 minutes 35 seconds'},{title:'The moments between',aspect:'960 / 540',duration:'01:44',caption:'Wedding highlights · 1 minute 44 seconds'},{title:'A promise, in motion',aspect:'1 / 1',duration:'00:50',caption:'Wedding highlights · 50 seconds'},{title:'Under the trees',aspect:'4 / 5',duration:'00:05',caption:'Motion portrait · 5 seconds'}];
export const edits=[{photo:3,alt:'Couple sitting together in a boat',name:'River light',treatment:'WARM FILM',filter:'sepia(.28) saturate(.85) contrast(1.08) brightness(.97)',caption:'Warmth in the quiet moments.'},{photo:6,alt:'Couple sharing a quiet afternoon outdoors',name:'A quiet afternoon',treatment:'MONOCHROME',filter:'grayscale(1) contrast(1.15) brightness(.95)',caption:'Less colour. More expression.'},{photo:19,alt:'Couple in emerald outfits beside courtyard arches',name:'Together in emerald',treatment:'DEEP COLOUR',filter:'saturate(1.4) contrast(1.12) brightness(.88)',caption:'A little depth in the jewel tones.'},{photo:31,alt:'Couple in lilac and pale colours in the landscape',name:'A lilac afternoon',treatment:'SOFT FILM',filter:'sepia(.16) saturate(.72) contrast(.88) brightness(1.07)',caption:'Light, softened around the edges.'}];
export const photoURL=id=>`/assets/photo-${String(id).padStart(2,'0')}.jpg`;
